# Generated by Django 5.0.1 on 2024-01-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='map',
            field=models.BooleanField(default=False, verbose_name='Map'),
        ),
    ]
