# Generated by Django 5.0.1 on 2024-01-26 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('filter_categories', '0001_initial'),
        ('filters', '0001_initial'),
        ('period_filter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(auto_created=True, default=1)),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('audio', models.FileField(upload_to='audios')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(auto_created=True, default=1)),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='files')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(auto_created=True, default=1)),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(auto_created=True, default=1)),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location_name', models.CharField(max_length=100, verbose_name='Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=100, verbose_name='Province')),
            ],
        ),
        migrations.CreateModel(
            name='Vertual_reality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(auto_created=True, default=1)),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vr', models.FileField(upload_to='vr')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(auto_created=True, default=1)),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(upload_to='videos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, help_text='Click to upload an image', null=True, upload_to='sources', verbose_name='Click to upload an image')),
                ('content', models.TextField()),
                ('statehood', models.BooleanField(default=False, verbose_name='Statehood')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Select a category', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='categories.categories', verbose_name='Select a category')),
                ('category_filter', models.ForeignKey(help_text='Select a filter ', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='filter_categories.filter_cotegory', verbose_name='Select a filter ')),
                ('period_filter', models.ForeignKey(help_text='Select a period filter', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='period_filter.period_filter', verbose_name='Select a period filter')),
                ('select_filter', models.ForeignKey(help_text='Select a filter category', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='filters.filters', verbose_name='Select a filter category')),
                ('select_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.province')),
            ],
        ),
        migrations.CreateModel(
            name='Interive_contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(auto_created=True, default=1)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='interive_contents', verbose_name='Interive file')),
                ('interive_contents', models.ForeignKey(limit_choices_to={'model__in': ('audios', 'videos', 'gallery', 'files', 'location', 'vertual_reality')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('interive_contents_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interive_set', to='sources.sources', verbose_name='Interive contents')),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(auto_created=True, default=1)),
                ('title', models.CharField(help_text='Content title', max_length=255, verbose_name='Content title')),
                ('text', models.TextField(verbose_name='')),
                ('contents', models.ForeignKey(help_text='Contents', max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='content_set', to='sources.sources', verbose_name='Contents')),
            ],
        ),
        migrations.CreateModel(
            name='Atribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(auto_created=True, default=1)),
                ('title', models.CharField(help_text='Atribute title', max_length=255, verbose_name='Atribute title')),
                ('description', models.CharField(help_text='Atribute description', max_length=255, verbose_name='Atribute description')),
                ('atribute', models.ForeignKey(help_text='Atributes', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='sources.sources', verbose_name='Atributes')),
            ],
        ),
    ]
