# Generated by Django 5.0.1 on 2024-01-26 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_categories', '0001_initial'),
        ('filters', '0002_alter_filters_category'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='select_filter',
            field=models.ForeignKey(help_text='Select a filter category', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='filter_categories.filter_cotegory', verbose_name='Select a filter category'),
        ),
        migrations.CreateModel(
            name='Select_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_filter', models.ForeignKey(help_text='Select a filter ', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='filters.filters', verbose_name='Select a filter ')),
            ],
        ),
        migrations.AlterField(
            model_name='sources',
            name='category_filter',
            field=models.ForeignKey(help_text='Select a filter ', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.select_filter', verbose_name='Select a filter '),
        ),
    ]
