# Generated by Django 5.0.1 on 2024-01-26 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_alter_filters_category'),
        ('sources', '0002_alter_sources_select_filter_select_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='category_filter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filters.filters', verbose_name='Select a filter'),
        ),
        migrations.RemoveField(
            model_name='sources',
            name='select_province',
        ),
        migrations.DeleteModel(
            name='Select_filter',
        ),
    ]
