# Generated by Django 5.0.1 on 2024-01-26 13:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_alter_sources_category_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sources',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
